#! /usr/bin/env bash

VCF=${VCF:-} # mandatory. genotype file
ARG=${ARG:-} # mandatory. EPACTS arguments
OUT=${OUT:-} # mandatory. output prefix

# Prepare Programs
module load epacts
NPROC=`cat /proc/cpuinfo | grep processor | wc -l`

# Run analysis
$EPACTSRUN epacts group --vcf $VCF $ARG --out $OUT
$EPACTSRUN make -f $OUT.Makefile -j $((NPROC-2))
